name: evm
proxy:
  appserver:
    - evm.lndo.site
  remix:
    - remix.evm.lndo.site
services:
  appserver:
    type: node:16
    install_dependencies_as_me:
      - npm install -g npm
      - npm install -g ganache-cli truffle
  remix:
    type: node:14
    port: '8080'
    webroot: remix-project
    build:
      - npm install -g yarn
      - yarn global add @nrwl/cli
      - git clone https://github.com/ethereum/remix-project.git
      - cd /app/remix-project && yarn install
      - cd /app/remix-project && yarn run build:libs
      - cd /app/remix-project && npx nx build
    command: cd /app/remix-project && npx nx serve
tooling:
  node:
    service: appserver
  npm:
    service: appserver
  npx:
    service: appserver
  truffle:
    service: appserver
  ganache-cli:
    service: appserver
  nx:
    service: remix
    dir: /app/remix-project
    command: npx nx
  yarn:
    service: remix
    dir: /app/remix-project